api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Containers/BlogSection/ArticleContainer/UI/ApiPlatform/Resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
