doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            ArticleContainer:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/BlogSection/ArticleContainer/Models'
                prefix: 'App\Containers\BlogSection\ArticleContainer\Models'
                alias: ArticleContainer
            CommentContainer:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/BlogSection/CommentContainer/Models'
                prefix: 'App\Containers\BlogSection\CommentContainer\Models'
                alias: CommentContainer
            UserContainer:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/UserContainer/Models'
                prefix: 'App\Containers\UserContainer\Models'
                alias: CommentContainer
        resolve_target_entities:
            App\Containers\BlogSection\ArticleContainer\Models\Interfaces\ArticleInterface: App\Containers\BlogSection\ArticleContainer\Models\Article
            App\Containers\BlogSection\ArticleContainer\Models\Interfaces\AuthorInterface: App\Containers\BlogSection\ArticleContainer\Models\Author
            App\Containers\BlogSection\CommentContainer\Models\Interfaces\CommentInterface: App\Containers\BlogSection\CommentContainer\Models\Comment
            App\Containers\UserContainer\Models\Interfaces\UserInterface: App\Containers\UserContainer\Models\User