doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            accounting_section_account_container:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/AccountingSection/AccountContainer/Models'
                prefix: App\Containers\AccountingSection\AccountContainer\Models
                alias: accounting_section_account_container
            accounting_section_transaction_container:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/AccountingSection/TransactionContainer/Models'
                prefix: App\Containers\AccountingSection\TransactionContainer\Models
                alias: accounting_section_transaction_container
            blog_section_article_container:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/BlogSection/ArticleContainer/Data/Entities'
                prefix: App\Containers\BlogSection\ArticleContainer\Models
                alias: blog_section_article_container
            blog_section_comment_container:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/BlogSection/CommentContainer/Data/Entities'
                prefix: App\Containers\BlogSection\CommentContainer\Models
                alias: blog_section_comment_container
            security_section_security_user_container:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/SecuritySection/SecurityUserContainer/Models'
                prefix: App\Containers\SecuritySection\SecurityUserContainer\Models
                alias: security_section_security_user_container
            user_container:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Containers/UserContainer/Models'
                prefix: App\Containers\UserContainer\Models
                alias: user_container
        resolve_target_entities:
            App\Containers\AccountingSection\AccountContainer\Models\Interfaces\OwnerInterface: App\Containers\AccountingSection\AccountContainer\Models\Owner
            App\Containers\AccountingSection\TransactionContainer\Models\Interfaces\AccountInterface: App\Containers\AccountingSection\TransactionContainer\Models\Account
            App\Containers\BlogSection\ArticleContainer\Models\Interfaces\AuthorInterface: App\Containers\BlogSection\ArticleContainer\Models\Author
            App\Containers\BlogSection\CommentContainer\Models\Interfaces\AuthorInterface: App\Containers\BlogSection\CommentContainer\Models\Author
            App\Containers\BlogSection\CommentContainer\Models\Interfaces\ArticleInterface: App\Containers\BlogSection\CommentContainer\Models\Article
            App\Containers\SecuritySection\SecurityUserContainer\Models\Interfaces\SecurityUserInterface: App\Containers\SecuritySection\SecurityUserContainer\Models\SecurityUser