framework:
    messenger:
        failure_transport: failed

        transports:
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            async: 'doctrine://default?queue_name=default'

        routing:
            App\Containers\AccountingSection\TransactionContainer\Dependencies\Messages\TransactionCreatedMessage: sync
            App\Containers\SecuritySection\RegistrationContainer\Dependencies\Messages\UserRegisteredMessage: sync
            App\Containers\SecuritySection\SecurityUserContainer\Dependencies\Messages\SecurityUserCreatedMessage: sync
            App\Containers\UserContainer\Dependencies\Messages\UserProfileUpdatedMessage: sync